# Generated by Django 5.2.4 on 2025-07-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrcet', '0003_csd_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='csd',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
